// layout: 하위 page.js들에게 공통적으로 적용됨. 보통 header, footer를 많이 정의

import NavBar from "@/components/NavBar";
import "./globals.css";
import { Cabin } from "next/font/google";
import Footer from "@/components/Footer";

// global font 설정: next/font 활용하기, Google Variable Fonts
const cabin = Cabin({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cabin.className}>
      <body className="w-full overflow-auto">
        {/* z-index: 컴포넌트들이 겹칠때 어떤 것이 앞으로 가는지, 숫자가 클수록 앞으로 */}
        {/* max-w-screen-? mx-auto: Responsive Design을 위해서 앱의 컨텐츠 양쪽에 공백주기 */}
        <header className="top-0 z-10 bg-yellow-50">
          <div className="max-w-screen-2xl mx-auto">
            <NavBar />
          </div>
        </header>
        <main className="w-full flex justify-center max-w-screen-xl mx-auto">
          {children}
        </main>
        <footer className="bottom-0 fixed w-full bg-purple-50">
          <div className="max-w-screen-2xl mx-auto">
            <Footer />
          </div>
        </footer>
      </body>
    </html>
  );
}
